# see: http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 3.7
    - 3.8

# see: http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

[testenv:]
passenv = 
whitelist_externals =
    bash
        bats
            git
                rpm
                    systemctl
                        nc
                            grep

                            c
install:
    - pip install tox-travis
script:
    - tox
after_success:
  - coveralls
notifications:
    email:
        recipients:
            - satoru.satoh+github@gmail.com
        on_failure: always
