# see: http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 3.6
    - 3.8

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38-ansible29

# see: http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

install:
    - pip install tox-travis
script:
    - tox
after_success:
  - coveralls
notifications:
    email:
        recipients:
            - satoru.satoh+github@gmail.com
        on_failure: always
