---
# yamllint disable-line rule:line-length
# Based on https://github.com/Azure-Samples/azure-pipelines-python/blob/master/.azure-pipelines/simple_package.1-multi-target.yml
# another ref. https://github.com/tox-dev/azure-pipelines-template
variables:
  package: pre_commit_hooks_for_ansible
  srcDirectory: src/
  testsDirectory: tests/$(package)

trigger:
  branches:
    include:
      - '*'

jobs:
  - job: Build
    strategy:
      matrix:
        python36:
          pythonVersion: 3.6
        python37:
          pythonVersion: 3.7
        python38:
          pythonVersion: 3.8

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      TOXENV: py${{ replace(variables['pythonVersion'], '.', '') }}

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)

      - script: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
        displayName: Install some more test time dependencies

      - bash: tox
        displayName: Run tests

# vim:sw=2:ts=2:et:
