---
# .. seealso:: https://github.com/ymyzk/tox-gh-actions
#
name: Tests inside container
# yamllint disable-line rule:truthy
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container: pycontribs/centos:8
    strategy:
      matrix:
        python-version:
          - 3.6

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox

# vim:sw=2:ts=2:et:
